### PR TITLE
Use `cc-assets` package for CC image assets

### LINKED ISSUE #381: Use `cc-assets` package for CC image assets
This project uses several Creative Commons image assets, such as license badges and icons. Currently, we are importing those image assets from the Vocabulary project, which has incorrect license terms for our CC Assets.

We have published a new [NPM package called `cc-assets`](https://www.npmjs.com/package/@creativecommons/cc-assets) containing the Creative Commons logos, icons, and license badges along with clarified LICENSE and TRADEMARK texts.

## Task

- [ ] switch to using the `cc-assets` package as the import source for CC image assets

### PR DESCRIPTION
**Pull request by MuluhGodson**
## Fixes

Fixes #381 by @brylie 

## Description
This PR replaces all images, logos and icons used in this Chooser project with equivalents from the `cc-assets` npm package.
Three assets not found in the `cc-assets` package are left untouched:
- `info.svg`
- `languange.png`
- `license-openness-scale.png`

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/components/FooterSection.vue [hunk 1]
```diff
@@ -7,15 +7,12 @@
...
-              xmlns="http://www.w3.org/2000/svg"
-              preserveAspectRatio="xMidYMid meet"
-              viewBox="0 0 304 73"
-            >
-              <use
-                href="~@creativecommons/vocabulary/assets/logos/cc/logomark.svg#logomark"
-              />
-            </svg>
+            <img
+              src="@creativecommons/vocabulary/assets/logos/cc/logomark.svg"
```
Comment (brylie) [inline src/components/FooterSection.vue:11]: We are preparing to deprecate the `@creativecommons/vocabulary` package. Use the `cc-assets` package instead.

**Review by brylie — CHANGES_REQUESTED** [review]

File: src/components/FooterSection.vue (hunk 1 above)
Comment (MuluhGodson) [reply src/components/FooterSection.vue:11]: Oh yeah let me correct that. Must have been a typo.

**Review by brylie — APPROVED** [review]
