### PR TITLE
Making link to work always as an absolute URL

### LINKED ISSUE #296: Make link to work always an absolute URL
## Description

When a user fills in the Attribution Details form, 'Mark your work' section is automatically updated. The URL from 'Link to Work' field is used as the URL for `href` attribute for the `<a>` anchor tag that includes the link to work in the RichText and HTML boxes. 

Currently, if a user provides a URL without the leading `http`, the `workUrl` computed prop adds `http://` to the start of URL to make it absolute. However, due to the bug, the result of this computed prop is not used, and instead, the URL becomes relative, not absolute.

## Reproduction

1. Select any license and go through the step to get to the last step, Attribution Details form.
2. Enter a URL without the leading `http`, i.e. `www.example.com/picture.jpg`
3. Look at the Richtext box in the 'Mark your work' section.
4. See error: the link in the attribution text becomes `https://chooser-beta.creativecommons.org/www.example.com/picture.jpg`.

image

## Expectation

The `href` attribute should be absolute, i.e. `http://www.example.com/picture.jpg` in the example.

## Additional context

Here is the line that needs to be changed:
https://github.com/creativecommons/chooser/blob/404fea77f103cf36fe54e8a3607eaf5ad0e8e1cf/src/components/LicenseText.vue#L120

## Resolution

- [ ] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by neeraj-2**
## Fixes

Fixes #296 by @obulat

## Description

It makes the URL absolute in the section of **Link to Work** in **Attribution Details**

## Technical details

While assigning href property, just check if the URL has HTTP as a part of the string or not. If not assign it manually

## Screenshots

image

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the *default* branch of the repository (`main` or `master`).
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by neeraj-2** [comment]
@obulat, I refactor the code something as I described above. Any other better approach you can suggest.

File: src/components/LicenseText.vue [hunk 1]
```diff
@@ -122,7 +119,9 @@ export default {
                 workAttrs.property = 'dct:title'
             }
             if (workUrl) {
-                workAttrs.href = workUrl
```
Comment (obulat) [inline src/components/LicenseText.vue:125]: I think it would be cleaner to replace 'workUrl' inside the 'workProps' function with 'this.workUrl'. This way, it will be using the value from the computed. You don't need to move the code from `workUrl` to `workProps`

File: src/components/LicenseText.vue [hunk 2]
```diff
@@ -122,7 +119,9 @@ export default {
                 workAttrs.property = 'dct:title'
```
Comment (obulat) [inline src/components/LicenseText.vue:119]: And in line 117, only destructure `workTitle` from `this.attributionDetails`, delete `workUrl` from there.

**Review by obulat — CHANGES_REQUESTED** [review]

File: src/components/LicenseText.vue (hunk 1 above)
Comment (neeraj-2) [reply src/components/LicenseText.vue:125]: Definitely, it would be cleaner and better

File: src/components/LicenseText.vue (hunk 2 above)
Comment (neeraj-2) [reply src/components/LicenseText.vue:122]: Done 👍

File: src/components/LicenseText.vue (hunk 1 above)
Comment (obulat) [reply src/components/LicenseText.vue:125]: Thank you for your contributions, @neeraj-2 !

**Review by obulat — APPROVED** [review]
