### PR TITLE
Fix persistence of `CopyrightWaiverStep` checkboxes

### LINKED ISSUE #323: State of CC0 waiver next button unconditionally retained
## Description

For an edge case at the CC0 step _Waive Your Copyright_, the checkboxes' states are incongruent with the `disabled` state of the _Next_ button.

## Reproduction

There are two paths to the CC0 license:

- Choosing it directly via _I know the license I need._
- Opting out of attribution via _Anyone can use my work, even without giving me attribution._

Going down one path until _Waive Your Copyright_, ticking both options and then going back and choosing the other path will result in the described incongruency.

## Expectation

_Next_ button should be disabled when arriving at _Waive Your Copyright_ (or checkboxes should save their state as well).

## Environment

 - Device: Laptop
 - OS: Fedora 32
 - Browser: Firefox
 - Version: 85.0.1

## Resolution

- [ ] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #323 

## Description

This PR moves the state of the `CopyrightWaiverStep` checkboxes into Vuex, so they persist when returning to the step from the following steps. This also establishes a pattern for steps with multiple checkboxes that we can use in #315 

## Technical details

This PR also models best practices for unit testing in Vue.js, namely, that _simulated user input should be used to test Vue internals._ In this case we're asserting that simulated checking of checkboxes triggers a Vue custom 'change' event in our Step component.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/store/index.js [hunk 1]
```diff
@@ -41,14 +59,16 @@ const createStore = (state) => {
...
     mutations: {
       /**
              * Updates current license attributes when user selects radio option.
              * Edge case: If user selects ND, SA should be set to false
              * @param state
-             * @param {string} name
-             * @param {Boolean} selected
+             * @param {Object} payload
+             * @param {string} payload.name
+             * @param {Boolean} payload.selected
```
Comment (zackkrida) [inline src/store/index.js:71]: Fixed this type definition even though it's outside the scope of this PR.

**Review by TimidRobot — APPROVED** [review]
good work!
